package com.budgetview.gui.utils;

import org.objectweb.asm.*;

import java.lang.reflect.Method;

public class KeyService {
  static final String checkSignature = "a";
  private static final String className = "a/b";

  public static boolean checkSignature(byte[] data, byte[] signature) {
    try {
      if (data == null || signature == null) {
        return false;
      }
      KeyClassLoader classLoader = new KeyClassLoader();
      Class<?> aClass = classLoader.load();
      Method method = aClass.getMethod(checkSignature, byte[].class, byte[].class);
      return (Boolean)method.invoke(null, data, signature);
    }
    catch (Exception e) {
      return false;
    }
  }

  private static class KeyClassLoader extends ClassLoader {

    public Class<?> load() throws Exception {
      byte[] b = KeyCheckerDump.dump();
      defineClass(className.replace('/', '.'), b, 0, b.length);
      return loadClass(className.replace('/', '.'));
    }
  }

  public static class KeyCheckerDump implements Opcodes {

    public static byte[] dump() throws Exception {

      ClassWriter cw = new ClassWriter(0);
      FieldVisitor fv;
      MethodVisitor mv;
      AnnotationVisitor av0;

      cw.visit(V1_5, ACC_PUBLIC + ACC_SUPER, className, null, "java/lang/Object", null);

      {
        fv = cw.visitField(ACC_PRIVATE + ACC_STATIC, "publicKey", "[B", null, null);
        fv.visitEnd();
      }
      {
        mv = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
        mv.visitCode();
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V");
        mv.visitInsn(RETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();
      }
      {
        mv = cw.visitMethod(ACC_PUBLIC + ACC_STATIC, checkSignature, "([B[B)Z", null, null);
        mv.visitCode();
        Label l0 = new Label();
        Label l1 = new Label();
        Label l2 = new Label();
        mv.visitTryCatchBlock(l0, l1, l2, "java/lang/Exception");
        mv.visitLabel(l0);
        mv.visitTypeInsn(NEW, "java/security/spec/X509EncodedKeySpec");
        mv.visitInsn(DUP);
        mv.visitFieldInsn(GETSTATIC, className, "publicKey", "[B");
        mv.visitMethodInsn(INVOKESPECIAL, "java/security/spec/X509EncodedKeySpec", "<init>", "([B)V");
        mv.visitVarInsn(ASTORE, 2);
        mv.visitLdcInsn("DSA");
        mv.visitLdcInsn("SUN");
        mv.visitMethodInsn(INVOKESTATIC, "java/security/KeyFactory", "getInstance", "(Ljava/lang/String;Ljava/lang/String;)Ljava/security/KeyFactory;");
        mv.visitVarInsn(ASTORE, 3);
        mv.visitVarInsn(ALOAD, 3);
        mv.visitVarInsn(ALOAD, 2);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/security/KeyFactory", "generatePublic", "(Ljava/security/spec/KeySpec;)Ljava/security/PublicKey;");
        mv.visitVarInsn(ASTORE, 4);
        mv.visitLdcInsn("SHA1withDSA");
        mv.visitLdcInsn("SUN");
        mv.visitMethodInsn(INVOKESTATIC, "java/security/Signature", "getInstance", "(Ljava/lang/String;Ljava/lang/String;)Ljava/security/Signature;");
        mv.visitVarInsn(ASTORE, 5);
        mv.visitVarInsn(ALOAD, 5);
        mv.visitVarInsn(ALOAD, 4);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/security/Signature", "initVerify", "(Ljava/security/PublicKey;)V");
        mv.visitVarInsn(ALOAD, 5);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/security/Signature", "update", "([B)V");
        mv.visitVarInsn(ALOAD, 5);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/security/Signature", "verify", "([B)Z");
        mv.visitLabel(l1);
        mv.visitInsn(IRETURN);
        mv.visitLabel(l2);
        mv.visitVarInsn(ASTORE, 2);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(IRETURN);
        mv.visitMaxs(3, 6);
        mv.visitEnd();
      }
      {
        mv = cw.visitMethod(ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitIntInsn(SIPUSH, 444);
        mv.visitIntInsn(NEWARRAY, T_BYTE);
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_0);
        mv.visitIntInsn(BIPUSH, 48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_1);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_2);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_3);
        mv.visitIntInsn(BIPUSH, -72);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_4);
        mv.visitIntInsn(BIPUSH, 48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_5);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 6);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 7);
        mv.visitIntInsn(BIPUSH, 44);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 8);
        mv.visitIntInsn(BIPUSH, 6);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 9);
        mv.visitIntInsn(BIPUSH, 7);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 10);
        mv.visitIntInsn(BIPUSH, 42);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 11);
        mv.visitIntInsn(BIPUSH, -122);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 12);
        mv.visitIntInsn(BIPUSH, 72);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 13);
        mv.visitIntInsn(BIPUSH, -50);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 14);
        mv.visitIntInsn(BIPUSH, 56);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 15);
        mv.visitInsn(ICONST_4);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 16);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 17);
        mv.visitIntInsn(BIPUSH, 48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 18);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 19);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 20);
        mv.visitIntInsn(BIPUSH, 31);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 21);
        mv.visitInsn(ICONST_2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 22);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 23);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 24);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 25);
        mv.visitIntInsn(BIPUSH, -3);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 26);
        mv.visitIntInsn(BIPUSH, 127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 27);
        mv.visitIntInsn(BIPUSH, 83);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 28);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 29);
        mv.visitIntInsn(BIPUSH, 29);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 30);
        mv.visitIntInsn(BIPUSH, 117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 31);
        mv.visitIntInsn(BIPUSH, 18);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 32);
        mv.visitIntInsn(BIPUSH, 41);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 33);
        mv.visitIntInsn(BIPUSH, 82);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 34);
        mv.visitIntInsn(BIPUSH, -33);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 35);
        mv.visitIntInsn(BIPUSH, 74);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 36);
        mv.visitIntInsn(BIPUSH, -100);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 37);
        mv.visitIntInsn(BIPUSH, 46);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 38);
        mv.visitIntInsn(BIPUSH, -20);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 39);
        mv.visitIntInsn(BIPUSH, -28);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 40);
        mv.visitIntInsn(BIPUSH, -25);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 41);
        mv.visitIntInsn(BIPUSH, -10);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 42);
        mv.visitIntInsn(BIPUSH, 17);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 43);
        mv.visitIntInsn(BIPUSH, -73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 44);
        mv.visitIntInsn(BIPUSH, 82);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 45);
        mv.visitIntInsn(BIPUSH, 60);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 46);
        mv.visitIntInsn(BIPUSH, -17);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 47);
        mv.visitIntInsn(BIPUSH, 68);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 48);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 49);
        mv.visitIntInsn(BIPUSH, -61);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 50);
        mv.visitIntInsn(BIPUSH, 30);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 51);
        mv.visitIntInsn(BIPUSH, 63);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 52);
        mv.visitIntInsn(BIPUSH, -128);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 53);
        mv.visitIntInsn(BIPUSH, -74);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 54);
        mv.visitIntInsn(BIPUSH, 81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 55);
        mv.visitIntInsn(BIPUSH, 38);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 56);
        mv.visitIntInsn(BIPUSH, 105);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 57);
        mv.visitIntInsn(BIPUSH, 69);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 58);
        mv.visitIntInsn(BIPUSH, 93);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 59);
        mv.visitIntInsn(BIPUSH, 64);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 60);
        mv.visitIntInsn(BIPUSH, 34);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 61);
        mv.visitIntInsn(BIPUSH, 81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 62);
        mv.visitIntInsn(BIPUSH, -5);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 63);
        mv.visitIntInsn(BIPUSH, 89);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 64);
        mv.visitIntInsn(BIPUSH, 61);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 65);
        mv.visitIntInsn(BIPUSH, -115);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 66);
        mv.visitIntInsn(BIPUSH, 88);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 67);
        mv.visitIntInsn(BIPUSH, -6);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 68);
        mv.visitIntInsn(BIPUSH, -65);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 69);
        mv.visitIntInsn(BIPUSH, -59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 70);
        mv.visitIntInsn(BIPUSH, -11);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 71);
        mv.visitIntInsn(BIPUSH, -70);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 72);
        mv.visitIntInsn(BIPUSH, 48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 73);
        mv.visitIntInsn(BIPUSH, -10);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 74);
        mv.visitIntInsn(BIPUSH, -53);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 75);
        mv.visitIntInsn(BIPUSH, -101);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 76);
        mv.visitIntInsn(BIPUSH, 85);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 77);
        mv.visitIntInsn(BIPUSH, 108);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 78);
        mv.visitIntInsn(BIPUSH, -41);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 79);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 80);
        mv.visitIntInsn(BIPUSH, 59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 81);
        mv.visitIntInsn(BIPUSH, -128);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 82);
        mv.visitIntInsn(BIPUSH, 29);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 83);
        mv.visitIntInsn(BIPUSH, 52);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 84);
        mv.visitIntInsn(BIPUSH, 111);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 85);
        mv.visitIntInsn(BIPUSH, -14);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 86);
        mv.visitIntInsn(BIPUSH, 102);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 87);
        mv.visitIntInsn(BIPUSH, 96);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 88);
        mv.visitIntInsn(BIPUSH, -73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 89);
        mv.visitIntInsn(BIPUSH, 107);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 90);
        mv.visitIntInsn(BIPUSH, -103);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 91);
        mv.visitIntInsn(BIPUSH, 80);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 92);
        mv.visitIntInsn(BIPUSH, -91);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 93);
        mv.visitIntInsn(BIPUSH, -92);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 94);
        mv.visitIntInsn(BIPUSH, -97);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 95);
        mv.visitIntInsn(BIPUSH, -97);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 96);
        mv.visitIntInsn(BIPUSH, -24);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 97);
        mv.visitInsn(ICONST_4);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 98);
        mv.visitIntInsn(BIPUSH, 123);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 99);
        mv.visitIntInsn(BIPUSH, 16);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 100);
        mv.visitIntInsn(BIPUSH, 34);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 101);
        mv.visitIntInsn(BIPUSH, -62);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 102);
        mv.visitIntInsn(BIPUSH, 79);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 103);
        mv.visitIntInsn(BIPUSH, -69);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 104);
        mv.visitIntInsn(BIPUSH, -87);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 105);
        mv.visitIntInsn(BIPUSH, -41);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 106);
        mv.visitIntInsn(BIPUSH, -2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 107);
        mv.visitIntInsn(BIPUSH, -73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 108);
        mv.visitIntInsn(BIPUSH, -58);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 109);
        mv.visitIntInsn(BIPUSH, 27);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 110);
        mv.visitIntInsn(BIPUSH, -8);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 111);
        mv.visitIntInsn(BIPUSH, 59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 112);
        mv.visitIntInsn(BIPUSH, 87);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 113);
        mv.visitIntInsn(BIPUSH, -25);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 114);
        mv.visitIntInsn(BIPUSH, -58);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 115);
        mv.visitIntInsn(BIPUSH, -88);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 116);
        mv.visitIntInsn(BIPUSH, -90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 117);
        mv.visitIntInsn(BIPUSH, 21);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 118);
        mv.visitIntInsn(BIPUSH, 15);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 119);
        mv.visitInsn(ICONST_4);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 120);
        mv.visitIntInsn(BIPUSH, -5);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 121);
        mv.visitIntInsn(BIPUSH, -125);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 122);
        mv.visitIntInsn(BIPUSH, -10);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 123);
        mv.visitIntInsn(BIPUSH, -45);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 124);
        mv.visitIntInsn(BIPUSH, -59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 125);
        mv.visitIntInsn(BIPUSH, 30);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 126);
        mv.visitIntInsn(BIPUSH, -61);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(BIPUSH, 127);
        mv.visitInsn(ICONST_2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 128);
        mv.visitIntInsn(BIPUSH, 53);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 129);
        mv.visitIntInsn(BIPUSH, 84);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 130);
        mv.visitIntInsn(BIPUSH, 19);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 131);
        mv.visitIntInsn(BIPUSH, 90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 132);
        mv.visitIntInsn(BIPUSH, 22);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 133);
        mv.visitIntInsn(BIPUSH, -111);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 134);
        mv.visitIntInsn(BIPUSH, 50);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 135);
        mv.visitIntInsn(BIPUSH, -10);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 136);
        mv.visitIntInsn(BIPUSH, 117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 137);
        mv.visitIntInsn(BIPUSH, -13);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 138);
        mv.visitIntInsn(BIPUSH, -82);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 139);
        mv.visitIntInsn(BIPUSH, 43);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 140);
        mv.visitIntInsn(BIPUSH, 97);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 141);
        mv.visitIntInsn(BIPUSH, -41);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 142);
        mv.visitIntInsn(BIPUSH, 42);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 143);
        mv.visitIntInsn(BIPUSH, -17);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 144);
        mv.visitIntInsn(BIPUSH, -14);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 145);
        mv.visitIntInsn(BIPUSH, 34);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 146);
        mv.visitInsn(ICONST_3);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 147);
        mv.visitIntInsn(BIPUSH, 25);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 148);
        mv.visitIntInsn(BIPUSH, -99);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 149);
        mv.visitIntInsn(BIPUSH, -47);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 150);
        mv.visitIntInsn(BIPUSH, 72);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 151);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 152);
        mv.visitIntInsn(BIPUSH, -57);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 153);
        mv.visitInsn(ICONST_2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 154);
        mv.visitIntInsn(BIPUSH, 21);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 155);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 156);
        mv.visitIntInsn(BIPUSH, -105);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 157);
        mv.visitIntInsn(BIPUSH, 96);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 158);
        mv.visitIntInsn(BIPUSH, 80);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 159);
        mv.visitIntInsn(BIPUSH, -113);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 160);
        mv.visitIntInsn(BIPUSH, 21);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 161);
        mv.visitIntInsn(BIPUSH, 35);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 162);
        mv.visitIntInsn(BIPUSH, 11);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 163);
        mv.visitIntInsn(BIPUSH, -52);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 164);
        mv.visitIntInsn(BIPUSH, -78);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 165);
        mv.visitIntInsn(BIPUSH, -110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 166);
        mv.visitIntInsn(BIPUSH, -71);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 167);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 168);
        mv.visitIntInsn(BIPUSH, -94);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 169);
        mv.visitIntInsn(BIPUSH, -21);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 170);
        mv.visitIntInsn(BIPUSH, -124);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 171);
        mv.visitIntInsn(BIPUSH, 11);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 172);
        mv.visitIntInsn(BIPUSH, -16);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 173);
        mv.visitIntInsn(BIPUSH, 88);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 174);
        mv.visitIntInsn(BIPUSH, 28);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 175);
        mv.visitIntInsn(BIPUSH, -11);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 176);
        mv.visitInsn(ICONST_2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 177);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 178);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 179);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 180);
        mv.visitIntInsn(BIPUSH, -9);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 181);
        mv.visitIntInsn(BIPUSH, -31);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 182);
        mv.visitIntInsn(BIPUSH, -96);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 183);
        mv.visitIntInsn(BIPUSH, -123);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 184);
        mv.visitIntInsn(BIPUSH, -42);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 185);
        mv.visitIntInsn(BIPUSH, -101);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 186);
        mv.visitIntInsn(BIPUSH, 61);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 187);
        mv.visitIntInsn(BIPUSH, -34);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 188);
        mv.visitIntInsn(BIPUSH, -53);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 189);
        mv.visitIntInsn(BIPUSH, -68);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 190);
        mv.visitIntInsn(BIPUSH, -85);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 191);
        mv.visitIntInsn(BIPUSH, 92);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 192);
        mv.visitIntInsn(BIPUSH, 54);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 193);
        mv.visitIntInsn(BIPUSH, -72);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 194);
        mv.visitIntInsn(BIPUSH, 87);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 195);
        mv.visitIntInsn(BIPUSH, -71);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 196);
        mv.visitIntInsn(BIPUSH, 121);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 197);
        mv.visitIntInsn(BIPUSH, -108);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 198);
        mv.visitIntInsn(BIPUSH, -81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 199);
        mv.visitIntInsn(BIPUSH, -69);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 200);
        mv.visitIntInsn(BIPUSH, -6);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 201);
        mv.visitIntInsn(BIPUSH, 58);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 202);
        mv.visitIntInsn(BIPUSH, -22);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 203);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 204);
        mv.visitIntInsn(BIPUSH, -7);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 205);
        mv.visitIntInsn(BIPUSH, 87);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 206);
        mv.visitIntInsn(BIPUSH, 76);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 207);
        mv.visitIntInsn(BIPUSH, 11);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 208);
        mv.visitIntInsn(BIPUSH, 61);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 209);
        mv.visitIntInsn(BIPUSH, 7);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 210);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 211);
        mv.visitIntInsn(BIPUSH, 103);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 212);
        mv.visitIntInsn(BIPUSH, 81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 213);
        mv.visitIntInsn(BIPUSH, 89);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 214);
        mv.visitIntInsn(BIPUSH, 87);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 215);
        mv.visitIntInsn(BIPUSH, -114);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 216);
        mv.visitIntInsn(BIPUSH, -70);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 217);
        mv.visitIntInsn(BIPUSH, -44);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 218);
        mv.visitIntInsn(BIPUSH, 89);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 219);
        mv.visitIntInsn(BIPUSH, 79);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 220);
        mv.visitIntInsn(BIPUSH, -26);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 221);
        mv.visitIntInsn(BIPUSH, 113);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 222);
        mv.visitIntInsn(BIPUSH, 7);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 223);
        mv.visitIntInsn(BIPUSH, 16);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 224);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 225);
        mv.visitIntInsn(BIPUSH, -128);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 226);
        mv.visitIntInsn(BIPUSH, -76);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 227);
        mv.visitIntInsn(BIPUSH, 73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 228);
        mv.visitIntInsn(BIPUSH, 22);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 229);
        mv.visitIntInsn(BIPUSH, 113);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 230);
        mv.visitIntInsn(BIPUSH, 35);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 231);
        mv.visitIntInsn(BIPUSH, -24);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 232);
        mv.visitIntInsn(BIPUSH, 76);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 233);
        mv.visitIntInsn(BIPUSH, 40);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 234);
        mv.visitIntInsn(BIPUSH, 22);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 235);
        mv.visitIntInsn(BIPUSH, 19);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 236);
        mv.visitIntInsn(BIPUSH, -73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 237);
        mv.visitIntInsn(BIPUSH, -49);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 238);
        mv.visitIntInsn(BIPUSH, 9);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 239);
        mv.visitIntInsn(BIPUSH, 50);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 240);
        mv.visitIntInsn(BIPUSH, -116);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 241);
        mv.visitIntInsn(BIPUSH, -56);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 242);
        mv.visitIntInsn(BIPUSH, -90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 243);
        mv.visitIntInsn(BIPUSH, -31);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 244);
        mv.visitIntInsn(BIPUSH, 60);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 245);
        mv.visitIntInsn(BIPUSH, 22);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 246);
        mv.visitIntInsn(BIPUSH, 122);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 247);
        mv.visitIntInsn(BIPUSH, -117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 248);
        mv.visitIntInsn(BIPUSH, 84);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 249);
        mv.visitIntInsn(BIPUSH, 124);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 250);
        mv.visitIntInsn(BIPUSH, -115);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 251);
        mv.visitIntInsn(BIPUSH, 40);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 252);
        mv.visitIntInsn(BIPUSH, -32);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 253);
        mv.visitIntInsn(BIPUSH, -93);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 254);
        mv.visitIntInsn(BIPUSH, -82);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 255);
        mv.visitIntInsn(BIPUSH, 30);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 256);
        mv.visitIntInsn(BIPUSH, 43);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 257);
        mv.visitIntInsn(BIPUSH, -77);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 258);
        mv.visitIntInsn(BIPUSH, -90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 259);
        mv.visitIntInsn(BIPUSH, 117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 260);
        mv.visitIntInsn(BIPUSH, -111);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 261);
        mv.visitIntInsn(BIPUSH, 110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 262);
        mv.visitIntInsn(BIPUSH, -93);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 263);
        mv.visitIntInsn(BIPUSH, 127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 264);
        mv.visitIntInsn(BIPUSH, 11);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 265);
        mv.visitIntInsn(BIPUSH, -6);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 266);
        mv.visitIntInsn(BIPUSH, 33);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 267);
        mv.visitIntInsn(BIPUSH, 53);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 268);
        mv.visitIntInsn(BIPUSH, 98);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 269);
        mv.visitIntInsn(BIPUSH, -15);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 270);
        mv.visitIntInsn(BIPUSH, -5);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 271);
        mv.visitIntInsn(BIPUSH, 98);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 272);
        mv.visitIntInsn(BIPUSH, 122);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 273);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 274);
        mv.visitIntInsn(BIPUSH, 36);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 275);
        mv.visitIntInsn(BIPUSH, 59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 276);
        mv.visitIntInsn(BIPUSH, -52);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 277);
        mv.visitIntInsn(BIPUSH, -92);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 278);
        mv.visitIntInsn(BIPUSH, -15);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 279);
        mv.visitIntInsn(BIPUSH, -66);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 280);
        mv.visitIntInsn(BIPUSH, -88);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 281);
        mv.visitIntInsn(BIPUSH, 81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 282);
        mv.visitIntInsn(BIPUSH, -112);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 283);
        mv.visitIntInsn(BIPUSH, -119);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 284);
        mv.visitIntInsn(BIPUSH, -88);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 285);
        mv.visitIntInsn(BIPUSH, -125);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 286);
        mv.visitIntInsn(BIPUSH, -33);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 287);
        mv.visitIntInsn(BIPUSH, -31);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 288);
        mv.visitIntInsn(BIPUSH, 90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 289);
        mv.visitIntInsn(BIPUSH, -27);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 290);
        mv.visitIntInsn(BIPUSH, -97);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 291);
        mv.visitIntInsn(BIPUSH, 6);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 292);
        mv.visitIntInsn(BIPUSH, -110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 293);
        mv.visitIntInsn(BIPUSH, -117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 294);
        mv.visitIntInsn(BIPUSH, 102);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 295);
        mv.visitIntInsn(BIPUSH, 94);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 296);
        mv.visitIntInsn(BIPUSH, -128);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 297);
        mv.visitIntInsn(BIPUSH, 123);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 298);
        mv.visitIntInsn(BIPUSH, 85);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 299);
        mv.visitIntInsn(BIPUSH, 37);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 300);
        mv.visitIntInsn(BIPUSH, 100);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 301);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 302);
        mv.visitIntInsn(BIPUSH, 76);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 303);
        mv.visitIntInsn(BIPUSH, 59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 304);
        mv.visitIntInsn(BIPUSH, -2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 305);
        mv.visitIntInsn(BIPUSH, -49);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 306);
        mv.visitIntInsn(BIPUSH, 73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 307);
        mv.visitIntInsn(BIPUSH, 42);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 308);
        mv.visitInsn(ICONST_3);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 309);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 310);
        mv.visitIntInsn(BIPUSH, -123);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 311);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 312);
        mv.visitInsn(ICONST_2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 313);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 314);
        mv.visitIntInsn(BIPUSH, -127);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 315);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 316);
        mv.visitIntInsn(BIPUSH, -56);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 317);
        mv.visitIntInsn(BIPUSH, -117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 318);
        mv.visitIntInsn(BIPUSH, 90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 319);
        mv.visitIntInsn(BIPUSH, 44);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 320);
        mv.visitIntInsn(BIPUSH, 80);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 321);
        mv.visitIntInsn(BIPUSH, 46);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 322);
        mv.visitIntInsn(BIPUSH, 71);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 323);
        mv.visitIntInsn(BIPUSH, 91);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 324);
        mv.visitIntInsn(BIPUSH, -77);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 325);
        mv.visitIntInsn(BIPUSH, -40);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 326);
        mv.visitIntInsn(BIPUSH, -39);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 327);
        mv.visitIntInsn(BIPUSH, 64);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 328);
        mv.visitIntInsn(BIPUSH, -87);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 329);
        mv.visitIntInsn(BIPUSH, -9);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 330);
        mv.visitIntInsn(BIPUSH, 65);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 331);
        mv.visitIntInsn(BIPUSH, -115);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 332);
        mv.visitIntInsn(BIPUSH, 65);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 333);
        mv.visitIntInsn(BIPUSH, -67);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 334);
        mv.visitIntInsn(BIPUSH, -103);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 335);
        mv.visitIntInsn(BIPUSH, -113);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 336);
        mv.visitIntInsn(BIPUSH, 62);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 337);
        mv.visitIntInsn(BIPUSH, 120);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 338);
        mv.visitIntInsn(BIPUSH, 19);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 339);
        mv.visitIntInsn(BIPUSH, 81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 340);
        mv.visitIntInsn(BIPUSH, -113);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 341);
        mv.visitIntInsn(BIPUSH, 110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 342);
        mv.visitIntInsn(BIPUSH, 48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 343);
        mv.visitIntInsn(BIPUSH, -30);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 344);
        mv.visitIntInsn(BIPUSH, -111);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 345);
        mv.visitIntInsn(BIPUSH, 35);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 346);
        mv.visitIntInsn(BIPUSH, -110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 347);
        mv.visitIntInsn(BIPUSH, 31);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 348);
        mv.visitIntInsn(BIPUSH, 72);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 349);
        mv.visitIntInsn(BIPUSH, -120);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 350);
        mv.visitIntInsn(BIPUSH, -107);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 351);
        mv.visitIntInsn(BIPUSH, 6);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 352);
        mv.visitIntInsn(BIPUSH, 39);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 353);
        mv.visitIntInsn(BIPUSH, -25);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 354);
        mv.visitIntInsn(BIPUSH, -49);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 355);
        mv.visitIntInsn(BIPUSH, -39);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 356);
        mv.visitIntInsn(BIPUSH, 36);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 357);
        mv.visitIntInsn(BIPUSH, -65);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 358);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 359);
        mv.visitIntInsn(BIPUSH, -126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 360);
        mv.visitIntInsn(BIPUSH, -102);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 361);
        mv.visitIntInsn(BIPUSH, -95);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 362);
        mv.visitIntInsn(BIPUSH, -117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 363);
        mv.visitIntInsn(BIPUSH, -93);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 364);
        mv.visitIntInsn(BIPUSH, -92);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 365);
        mv.visitIntInsn(BIPUSH, 12);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 366);
        mv.visitIntInsn(BIPUSH, -74);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 367);
        mv.visitIntInsn(BIPUSH, -82);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 368);
        mv.visitIntInsn(BIPUSH, 126);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 369);
        mv.visitIntInsn(BIPUSH, -55);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 370);
        mv.visitIntInsn(BIPUSH, 80);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 371);
        mv.visitIntInsn(BIPUSH, 121);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 372);
        mv.visitIntInsn(BIPUSH, -89);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 373);
        mv.visitIntInsn(BIPUSH, -108);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 374);
        mv.visitIntInsn(BIPUSH, 110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 375);
        mv.visitIntInsn(BIPUSH, -110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 376);
        mv.visitIntInsn(BIPUSH, -78);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 377);
        mv.visitIntInsn(BIPUSH, -30);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 378);
        mv.visitIntInsn(BIPUSH, 66);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 379);
        mv.visitIntInsn(BIPUSH, -108);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 380);
        mv.visitIntInsn(BIPUSH, 68);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 381);
        mv.visitIntInsn(BIPUSH, -75);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 382);
        mv.visitIntInsn(BIPUSH, -63);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 383);
        mv.visitIntInsn(BIPUSH, -106);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 384);
        mv.visitIntInsn(BIPUSH, 73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 385);
        mv.visitIntInsn(BIPUSH, -65);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 386);
        mv.visitIntInsn(BIPUSH, 41);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 387);
        mv.visitIntInsn(BIPUSH, 23);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 388);
        mv.visitIntInsn(BIPUSH, 65);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 389);
        mv.visitIntInsn(BIPUSH, -77);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 390);
        mv.visitIntInsn(BIPUSH, 79);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 391);
        mv.visitIntInsn(BIPUSH, 69);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 392);
        mv.visitIntInsn(BIPUSH, -125);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 393);
        mv.visitIntInsn(BIPUSH, -70);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 394);
        mv.visitIntInsn(BIPUSH, -92);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 395);
        mv.visitIntInsn(BIPUSH, 86);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 396);
        mv.visitIntInsn(BIPUSH, 110);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 397);
        mv.visitIntInsn(BIPUSH, -57);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 398);
        mv.visitIntInsn(BIPUSH, 38);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 399);
        mv.visitIntInsn(BIPUSH, -14);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 400);
        mv.visitIntInsn(BIPUSH, -124);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 401);
        mv.visitIntInsn(BIPUSH, 90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 402);
        mv.visitIntInsn(BIPUSH, -51);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 403);
        mv.visitIntInsn(BIPUSH, -56);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 404);
        mv.visitIntInsn(BIPUSH, 43);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 405);
        mv.visitIntInsn(BIPUSH, 79);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 406);
        mv.visitIntInsn(BIPUSH, 104);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 407);
        mv.visitIntInsn(BIPUSH, 107);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 408);
        mv.visitIntInsn(BIPUSH, 125);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 409);
        mv.visitIntInsn(BIPUSH, 91);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 410);
        mv.visitIntInsn(BIPUSH, -81);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 411);
        mv.visitIntInsn(BIPUSH, 59);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 412);
        mv.visitIntInsn(BIPUSH, 69);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 413);
        mv.visitIntInsn(BIPUSH, -48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 414);
        mv.visitIntInsn(BIPUSH, 22);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 415);
        mv.visitIntInsn(BIPUSH, 69);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 416);
        mv.visitIntInsn(BIPUSH, 41);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 417);
        mv.visitIntInsn(BIPUSH, -99);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 418);
        mv.visitIntInsn(BIPUSH, 99);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 419);
        mv.visitIntInsn(BIPUSH, 38);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 420);
        mv.visitIntInsn(BIPUSH, 90);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 421);
        mv.visitIntInsn(BIPUSH, 44);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 422);
        mv.visitIntInsn(BIPUSH, 70);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 423);
        mv.visitIntInsn(BIPUSH, 20);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 424);
        mv.visitIntInsn(BIPUSH, -48);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 425);
        mv.visitIntInsn(BIPUSH, 68);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 426);
        mv.visitIntInsn(BIPUSH, 24);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 427);
        mv.visitIntInsn(BIPUSH, 46);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 428);
        mv.visitIntInsn(BIPUSH, 14);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 429);
        mv.visitIntInsn(BIPUSH, -67);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 430);
        mv.visitIntInsn(BIPUSH, 111);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 431);
        mv.visitIntInsn(BIPUSH, -8);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 432);
        mv.visitIntInsn(BIPUSH, 52);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 433);
        mv.visitIntInsn(BIPUSH, 94);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 434);
        mv.visitIntInsn(BIPUSH, 36);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 435);
        mv.visitIntInsn(BIPUSH, 73);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 436);
        mv.visitIntInsn(BIPUSH, -117);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 437);
        mv.visitIntInsn(BIPUSH, -43);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 438);
        mv.visitIntInsn(BIPUSH, -2);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 439);
        mv.visitIntInsn(BIPUSH, 31);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 440);
        mv.visitIntInsn(BIPUSH, 95);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 441);
        mv.visitIntInsn(BIPUSH, -111);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 442);
        mv.visitIntInsn(BIPUSH, -118);
        mv.visitInsn(BASTORE);
        mv.visitInsn(DUP);
        mv.visitIntInsn(SIPUSH, 443);
        mv.visitIntInsn(BIPUSH, 124);
        mv.visitInsn(BASTORE);
        mv.visitFieldInsn(PUTSTATIC, className, "publicKey", "[B");
        mv.visitInsn(RETURN);
        mv.visitMaxs(4, 0);
        mv.visitEnd();
      }
      cw.visitEnd();

      return cw.toByteArray();
    }
  }

}
