package com.budgetview.cloud.functests;

import com.budgetview.cloud.functests.utils.CloudTestCase;

public class BudgeaCallbackTest extends CloudTestCase {

  public void test() throws Exception {
    budgea.callWebhook("{" +
                       "  'connections':[" +
                       "    {" +
                       "      'id_user':476," +
                       "      'subscriptions':[" +
                       "      ]," +
                       "      'id_bank':40," +
                       "      'last_update':'2016-08-08 14:12:55'," +
                       "      'expire':null," +
                       "      'accounts':[" +
                       "        {" +
                       "          'last_update':'2016-08-08 14:12:46'," +
                       "          'formatted_balance':'5953,84 €'," +
                       "          'name':'Compte chèque'," +
                       "          'transactions':[" +
                       "          ]," +
                       "          'deleted':null," +
                       "          'id_connection':272," +
                       "          'original_name':'Compte chèque'," +
                       "          'number':'3002900000'," +
                       "          'display':true," +
                       "          'currency':{" +
                       "            'symbol':'€'," +
                       "            'prefix':false," +
                       "            'id':'EUR'" +
                       "          }," +
                       "          'iban':'FR7613696539985300290000088'," +
                       "          'coming':null," +
                       "          'investments':[" +
                       "          ]," +
                       "          'balance':5953.84," +
                       "          'type':'checking'," +
                       "          'id':629" +
                       "        }," +
                       "        {" +
                       "          'last_update':'2016-08-08 14:12:48'," +
                       "          'formatted_balance':'1480,02 €'," +
                       "          'name':'Livret A'," +
                       "          'transactions':[" +
                       "          ]," +
                       "          'deleted':null," +
                       "          'id_connection':272," +
                       "          'original_name':'Livret A'," +
                       "          'number':'3002900001'," +
                       "          'display':true," +
                       "          'currency':{" +
                       "            'symbol':'€'," +
                       "            'prefix':false," +
                       "            'id':'EUR'" +
                       "          }," +
                       "          'iban':'FR7613696539985300290000185'," +
                       "          'coming':null," +
                       "          'investments':[" +
                       "          ]," +
                       "          'balance':1480.02," +
                       "          'type':'savings'," +
                       "          'id':632" +
                       "        }," +
                       "        {" +
                       "          'number':'3002900002'," +
                       "          'currency':{" +
                       "            'symbol':'€'," +
                       "            'prefix':false," +
                       "            'id':'EUR'" +
                       "          }," +
                       "          'diff':55.91," +
                       "          'id':635," +
                       "          'formatted_balance':'1829,99 €'," +
                       "          'id_connection':272," +
                       "          'original_name':'Assurance Vie'," +
                       "          'last_update':'2016-08-08 14:12:51'," +
                       "          'prev_diff_percent':0.241," +
                       "          'transactions':[" +
                       "          ]," +
                       "          'deleted':null," +
                       "          'iban':'FR7613696539985300290000282'," +
                       "          'coming':null," +
                       "          'valuation':1829.99," +
                       "          'name':'Assurance Vie'," +
                       "          'type':'lifeinsurance'," +
                       "          'calculated':[" +
                       "            'diff'," +
                       "            'diff_percent'," +
                       "            'prev_diff'," +
                       "            'prev_diff_percent'," +
                       "            'valuation'" +
                       "          ]," +
                       "          'prev_diff':354.89," +
                       "          'investments':[" +
                       "            {" +
                       "              'code':'FR0010330902'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.7000," +
                       "              'diff':13.44," +
                       "              'unitvalue':150.62," +
                       "              'id':1601," +
                       "              'original_unitprice':null," +
                       "              'id_account':635," +
                       "              'label':'Agressor PEA'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':1280.99," +
                       "              'id_security':4," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':0.241," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':248.59," +
                       "              'quantity':8.5050," +
                       "              'unitprice':149.04," +
                       "              'diff_percent':0.011" +
                       "            }," +
                       "            {" +
                       "              'code':'LU0304955437'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.2100," +
                       "              'diff':55.87," +
                       "              'unitvalue':57.88," +
                       "              'id':1604," +
                       "              'original_unitprice':null," +
                       "              'id_account':635," +
                       "              'label':'EDGEWOOD L SEL US SEL GW'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':384.30," +
                       "              'id_security':7," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':1.065," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':198.17," +
                       "              'quantity':6.6400," +
                       "              'unitprice':49.46," +
                       "              'diff_percent':0.17" +
                       "            }," +
                       "            {" +
                       "              'code':'FR0010773036'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0276," +
                       "              'diff':8.10," +
                       "              'unitvalue':23.60," +
                       "              'id':1607," +
                       "              'original_unitprice':null," +
                       "              'id_account':635," +
                       "              'label':'EDR GLOBAL CONVERTIBLES'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':50.59," +
                       "              'id_security':10," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':0.065," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':3.07," +
                       "              'quantity':2.1440," +
                       "              'unitprice':19.82," +
                       "              'diff_percent':0.191" +
                       "            }," +
                       "            {" +
                       "              'code':'FR0010479931'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0408," +
                       "              'diff':-17.63," +
                       "              'unitvalue':23.64," +
                       "              'id':1610," +
                       "              'original_unitprice':null," +
                       "              'id_account':635," +
                       "              'label':'EDR India'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':74.74," +
                       "              'id_security':13," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':13.345," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':69.53," +
                       "              'quantity':3.1610," +
                       "              'unitprice':29.22," +
                       "              'diff_percent':-0.191" +
                       "            }," +
                       "            {" +
                       "              'code':'XXEUROSSIMA'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0130," +
                       "              'diff':null," +
                       "              'unitvalue':null," +
                       "              'id':1613," +
                       "              'original_unitprice':null," +
                       "              'id_account':635," +
                       "              'label':'Fonds en euros (Eurossima)'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':23.76," +
                       "              'id_security':16," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':0.578," +
                       "              'calculated':[" +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':8.70," +
                       "              'quantity':null," +
                       "              'unitprice':null," +
                       "              'diff_percent':null" +
                       "            }," +
                       "            {" +
                       "              'code':'LU0119345287'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0085," +
                       "              'diff':-3.87," +
                       "              'unitvalue':5.98," +
                       "              'id':1616," +
                       "              'original_unitprice':null," +
                       "              'id_account':635," +
                       "              'label':'Pioneer Funds Euroland E'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':15.61," +
                       "              'id_security':19," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':-0.917," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':-173.17," +
                       "              'quantity':2.6090," +
                       "              'unitprice':7.47," +
                       "              'diff_percent':-0.199" +
                       "            }" +
                       "          ]," +
                       "          'balance':1829.99," +
                       "          'display':true," +
                       "          'diff_percent':0.032" +
                       "        }," +
                       "        {" +
                       "          'number':'3002900003'," +
                       "          'currency':{" +
                       "            'symbol':'€'," +
                       "            'prefix':false," +
                       "            'id':'EUR'" +
                       "          }," +
                       "          'diff':-89.49," +
                       "          'id':638," +
                       "          'formatted_balance':'2187,86 €'," +
                       "          'id_connection':272," +
                       "          'original_name':'Comptes titres'," +
                       "          'last_update':'2016-08-08 14:12:53'," +
                       "          'prev_diff_percent':-0.723," +
                       "          'transactions':[" +
                       "          ]," +
                       "          'deleted':null," +
                       "          'iban':'FR7613696539985300290000379'," +
                       "          'coming':null," +
                       "          'valuation':2187.86," +
                       "          'name':'Comptes titres'," +
                       "          'type':'market'," +
                       "          'calculated':[" +
                       "            'diff'," +
                       "            'diff_percent'," +
                       "            'prev_diff'," +
                       "            'prev_diff_percent'," +
                       "            'valuation'" +
                       "          ]," +
                       "          'prev_diff':-5724.10," +
                       "          'investments':[" +
                       "            {" +
                       "              'code':'FR0010330902'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.7000," +
                       "              'diff':-39.66," +
                       "              'unitvalue':356.16," +
                       "              'id':1619," +
                       "              'original_unitprice':null," +
                       "              'id_account':638," +
                       "              'label':'Agressor PEA'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':1531.50," +
                       "              'id_security':4," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':-0.723," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':-4006.87," +
                       "              'quantity':4.3000," +
                       "              'unitprice':365.39," +
                       "              'diff_percent':-0.025" +
                       "            }," +
                       "            {" +
                       "              'code':'LU0304955437'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.1073," +
                       "              'diff':-75.11," +
                       "              'unitvalue':26.15," +
                       "              'id':1622," +
                       "              'original_unitprice':null," +
                       "              'id_account':638," +
                       "              'label':'EDGEWOOD L SEL US SEL GW'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':234.84," +
                       "              'id_security':7," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':-0.859," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':-1426.67," +
                       "              'quantity':8.9820," +
                       "              'unitprice':34.51," +
                       "              'diff_percent':-0.242" +
                       "            }," +
                       "            {" +
                       "              'code':'FR0010773036'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0082," +
                       "              'diff':-1.56," +
                       "              'unitvalue':36.80," +
                       "              'id':1625," +
                       "              'original_unitprice':null," +
                       "              'id_account':638," +
                       "              'label':'EDR GLOBAL CONVERTIBLES'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':17.85," +
                       "              'id_security':10," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':-0.942," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':-289.27," +
                       "              'quantity':0.4850," +
                       "              'unitprice':40.02," +
                       "              'diff_percent':-0.08" +
                       "            }," +
                       "            {" +
                       "              'code':'FR0010479931'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0453," +
                       "              'diff':3.68," +
                       "              'unitvalue':268.03," +
                       "              'id':1628," +
                       "              'original_unitprice':null," +
                       "              'id_account':638," +
                       "              'label':'EDR India'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':99.17," +
                       "              'id_security':13," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':3.944," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':79.11," +
                       "              'quantity':0.3700," +
                       "              'unitprice':258.09," +
                       "              'diff_percent':0.039" +
                       "            }," +
                       "            {" +
                       "              'code':'XXEUROSSIMA'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.0073," +
                       "              'diff':null," +
                       "              'unitvalue':null," +
                       "              'id':1631," +
                       "              'original_unitprice':null," +
                       "              'id_account':638," +
                       "              'label':'Fonds en euros (Eurossima)'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':15.89," +
                       "              'id_security':16," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':-0.926," +
                       "              'calculated':[" +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':-198.65," +
                       "              'quantity':null," +
                       "              'unitprice':null," +
                       "              'diff_percent':null" +
                       "            }," +
                       "            {" +
                       "              'code':'LU0119345287'," +
                       "              'prev_vdate':'2016-08-08'," +
                       "              'original_valuation':null," +
                       "              'portfolio_share':0.1319," +
                       "              'diff':23.16," +
                       "              'unitvalue':98.30," +
                       "              'id':1634," +
                       "              'original_unitprice':null," +
                       "              'id_account':638," +
                       "              'label':'Pioneer Funds Euroland E'," +
                       "              'type':null," +
                       "              'description':''," +
                       "              'original_unitvalue':null," +
                       "              'original_currency':null," +
                       "              'original_diff':null," +
                       "              'id_type':null," +
                       "              'valuation':288.61," +
                       "              'id_security':19," +
                       "              'vdate':'2016-08-08'," +
                       "              'prev_diff_percent':0.694," +
                       "              'calculated':[" +
                       "                'diff_percent'," +
                       "                'prev_diff_percent'" +
                       "              ]," +
                       "              'prev_diff':118.25," +
                       "              'quantity':2.9360," +
                       "              'unitprice':90.41," +
                       "              'diff_percent':0.087" +
                       "            }" +
                       "          ]," +
                       "          'balance':2187.86," +
                       "          'display':true," +
                       "          'diff_percent':-0.039" +
                       "        }" +
                       "      ]," +
                       "      'error':null," +
                       "      'active':true," +
                       "      'id':272," +
                       "      'bank':{" +
                       "        'id_category':null," +
                       "        'code':null," +
                       "        'name':'Connecteur de test'," +
                       "        'capabilities':'set([])'," +
                       "        'beta':false," +
                       "        'hidden':false," +
                       "        'id':40," +
                       "        'charged':false" +
                       "      }" +
                       "    }" +
                       "  ]," +
                       "  'total':1," +
                       "  'user':{" +
                       "    'invites':[" +
                       "    ]," +
                       "    'signin':'2016-08-07 17:55:13'," +
                       "    'platform':'sharedAccess'," +
                       "    'alert_settings':{" +
                       "      'type':'transactions'," +
                       "      'balance_min2':0.00," +
                       "      'balance_min1':500.00," +
                       "      'balance_max':10000.00," +
                       "      'enabled':true," +
                       "      'date_range':null," +
                       "      'income_max':500.00," +
                       "      'value_type':'flat'," +
                       "      'accounts':null," +
                       "      'resume_enabled':true," +
                       "      'apply':null," +
                       "      'expense_max':500.00," +
                       "      'id':409" +
                       "    }," +
                       "    'config':{" +
                       "      'biapi.last_push':'2016-08-08 14:07:53'" +
                       "    }," +
                       "    'id':476" +
                       "  }" +
                       "}");
  }
}
